#!/bin/bash
total 48
drwxr-xr-x 2 root root 270 Dec  6 06:14 .
drwxr-xr-x 5 root root  91 Dec  6 05:38 ..
-rwxr--r-- 1 root root  32 Dec  5 19:06 0-hello_world
-rwxr--r-- 1 root root  27 Dec  5 19:12 1-confused_smiley
-rwxr--r-- 1 root root  28 Dec  5 19:30 2-hellofile
-rwxr--r-- 1 root root  39 Dec  5 19:34 3-twofiles
-rwxr--r-- 1 root root  29 Dec  5 19:48 4-lastlines
-rwxr--r-- 1 root root  29 Dec  5 19:50 5-firstlines
-rwxr--r-- 1 root root  38 Dec  6 05:29 6-third_line
-rwxr--r-- 1 root root  72 Dec  6 05:49 7-file
lrwxrwxrwx 1 root root  22 Dec  6 06:06 .#8-cwd_state -> root@1bb32f8c30a9.2455
-rwxr--r-- 1 root root  93 Dec  6 06:14 8-cwd_state
-rw-r--r-- 1 root root  42 Dec  5 20:42 9-duplicate_last_line
-rw-r--r-- 1 root root  12 Dec  6 06:15 ls_cwd_content
-rw-r--r-- 1 root root  18 Dec  5 18:40 README.md
